<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Login</name>
   <tag></tag>
   <elementGuidId>02e57a15-4b90-495e-a50b-b0f34022e63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fc14024-0252-4b47-8996-fdf895bbdfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-submit</value>
      <webElementGuid>f38d1c0a-ee4a-4766-9d4a-3e6cc30a1232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b132bf2c-a563-4654-bdaf-89537f3e7318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block</value>
      <webElementGuid>1255e6f8-0010-4bbd-91ad-552e42c4fec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitFormLogin(event);</value>
      <webElementGuid>cbceec02-69cf-4653-a418-35386d5c88fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Login                                            </value>
      <webElementGuid>d96a3ed1-2063-430e-b628-e8e19c33b40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-submit&quot;)</value>
      <webElementGuid>f800f7f9-e614-4857-adce-597d3f5474e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-submit']</value>
      <webElementGuid>83ba94c3-3f22-43b7-a11a-7a8dc83d3074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-4']/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>8fe4b25a-4afa-4640-9254-1e6f1387091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/following::button[1]</value>
      <webElementGuid>edff8902-6766-4a79-80be-47e285e24c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/following::button[1]</value>
      <webElementGuid>4543d8c6-918e-4475-9c41-1b28a822b3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Tanpa Kata Sandi'])[1]/preceding::button[1]</value>
      <webElementGuid>34794045-99dd-41df-9547-1763c7247a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mama,'])[1]/preceding::button[2]</value>
      <webElementGuid>303278a1-5115-4b70-91e5-5443b2b0319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>99319c5e-84bd-4b16-bb35-392d9b8984b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-submit' and @type = 'submit' and (text() = '
                                                Login                                            ' or . = '
                                                Login                                            ')]</value>
      <webElementGuid>e12f55db-05de-4f39-adb9-44d293c2bea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
