<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hiding Kata Sandi</name>
   <tag></tag>
   <elementGuidId>8b657b2c-6d96-44dc-b83f-d4e84cdc665a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.input-group-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-4']/div/div/div[2]/div/div[3]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6add4da-9675-4cc8-9b68-52bd2f28b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>bcf93367-8ba1-403e-9ef4-8dce8add0555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-4&quot;)/div[@class=&quot;row login__wrapper&quot;]/div[@class=&quot;col-10 offset-1 col-lg-10 offset-lg-2&quot;]/div[@class=&quot;content__card rounded&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 offset-md-2&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;showpassword input-group-append&quot;]/span[@class=&quot;input-group-text&quot;]</value>
      <webElementGuid>c10fe292-78a4-41fc-aa6c-b5197effd8a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-4']/div/div/div[2]/div/div[3]/div[2]/div/span</value>
      <webElementGuid>01802d90-a0aa-4470-a057-82e1796afaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/following::span[1]</value>
      <webElementGuid>5a809c23-948f-4a6c-8c4c-8c47d42fe197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone'])[1]/following::span[1]</value>
      <webElementGuid>8a8c3016-a0cd-4e99-8fe5-5eed97252a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/preceding::span[1]</value>
      <webElementGuid>4f049411-e067-4810-9548-46507cccb54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::span[1]</value>
      <webElementGuid>7fa9efeb-64a5-4f1d-aa6e-ef71d8fceaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>daae1a95-910c-48bf-9b5a-7d74276bb9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
