<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Kata Sandi</name>
   <tag></tag>
   <elementGuidId>983e3722-b9be-4f8c-8c05-950f48179c2d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-sfp6etonu7a6&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@title='reCAPTCHA']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'reCAPTCHA' and @name = 'a-sfp6etonu7a6' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=vjbW55W42X033PfTdVf6Ft4q&amp;theme=light&amp;size=normal&amp;cb=wzl0sv7wk3vz']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>13d6c041-48c6-4439-951b-8b017b8eb4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>0e339754-27cd-477a-9f06-300ce7cec702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>a5e392fb-14b0-46ef-93c4-1afbb747de0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>017532d6-ff9a-4288-84d7-fb0bf961c868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4d5f60f1-8000-4634-9fd7-33dfcae86d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-sfp6etonu7a6</value>
      <webElementGuid>e0239a70-b142-46c5-af53-2742c53fb462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>86142816-57ab-4dd7-96fb-359a53a2d1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5a2f07f0-8b31-4673-84b9-0952c229e70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>410623b3-d1ce-45ff-8ef8-2e7b09be2203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=vjbW55W42X033PfTdVf6Ft4q&amp;theme=light&amp;size=normal&amp;cb=wzl0sv7wk3vz</value>
      <webElementGuid>8a45defb-baa2-4b7a-9f62-3f4044217be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-login&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>610e627c-c67d-4703-9fe3-eccbd0af7aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-sfp6etonu7a6']</value>
      <webElementGuid>db37a4f6-618f-4a01-98b2-74d0c0a596e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-login']/div/div/iframe</value>
      <webElementGuid>9216c311-4093-4880-a2df-550020e1b753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>37799435-a831-48c5-a669-18150763bdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-sfp6etonu7a6' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfLXx4pAAAAAOL8JGqGwR4NGGa2pkdU0DCfCs8E&amp;co=aHR0cHM6Ly93d3cubnV0cmljbHViLmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=vjbW55W42X033PfTdVf6Ft4q&amp;theme=light&amp;size=normal&amp;cb=wzl0sv7wk3vz']</value>
      <webElementGuid>38a339ce-8ee8-4c86-948c-0de8bf7e481f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
