<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Agreement-Cookie</name>
   <tag></tag>
   <elementGuidId>d8284d62-5760-441e-937b-7ed20023cdb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agreementPrivacy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agreementPrivacy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98dba224-0ec2-446e-8a5b-cb23fe7824cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fffb2673-c643-46c5-bdc4-d548d3deb06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Agreement</value>
      <webElementGuid>35b9de60-ff7c-4d50-a755-28157de304db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreementPrivacy</value>
      <webElementGuid>c6bb6d25-c9ba-4bb2-aa52-d8cb892d21e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input p-0</value>
      <webElementGuid>57ae7e05-77ff-432f-ac24-925842d0e541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreementPrivacy&quot;)</value>
      <webElementGuid>0bbdf3ec-a039-42ae-9e7f-55b72e221ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agreementPrivacy']</value>
      <webElementGuid>a029ec26-892c-44d9-a95d-f5d6ea717b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>06b9451f-572e-41f7-a909-238f8722657c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Agreement' and @id = 'agreementPrivacy']</value>
      <webElementGuid>3330c3b8-1410-498d-95d8-d41d7fbe3f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
