<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Tanggal Lahir Anak</name>
   <tag></tag>
   <elementGuidId>8981e513-6464-485c-8c46-285778dfa629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1715572410646</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d364f7a-4f5d-4a1d-a18b-ac8b6bd70fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>681ae8d0-f641-49a5-ae0f-5f3339a94837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control childBirthday mb-2 hasDatepicker</value>
      <webElementGuid>4d19609a-290e-496d-a8b0-56c52c54c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jawaban</value>
      <webElementGuid>42ca957a-771a-4625-abd7-f3aff8c2f4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1715572410646</value>
      <webElementGuid>e6f7beb7-8a9e-4a80-a99a-8a06b7d3656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1715572410646&quot;)</value>
      <webElementGuid>30e55132-bc01-4d7e-ba23-78017d6ffa23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1715572410646']</value>
      <webElementGuid>7461bbdb-02ba-476b-a320-1ba0272fec0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='childDetailsWrapper']/div/div/div/input</value>
      <webElementGuid>be6fedf4-b27b-46b7-929c-d3639bf4a971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>b8b9d22f-7544-4d1c-ab2a-c2f7388f1fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Jawaban' and @id = 'dp1715572410646']</value>
      <webElementGuid>f20d1794-5d48-4774-8e0e-1237a5da5782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
