<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Kode Referal (opsional)</name>
   <tag></tag>
   <elementGuidId>ae2d8fa5-cc1c-4c33-8e9e-d56c28060644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refferalCodeEventCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refferalCodeEventCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>258b65af-76f3-46ac-8929-d56eb958dbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88f1529b-dbcb-490f-bdb9-b78589083638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>dc7e6ffb-9423-4848-8bb4-c11129c244b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>8e01abd4-b2e2-4f5c-ac62-45bcc1ff1d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>65248443-73ee-46a4-b5f3-332888a3a18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kode Referal Teman Anda Disini</value>
      <webElementGuid>de5a7392-fda9-42d7-be14-e64f046ed054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refferalCodeEventCode&quot;)</value>
      <webElementGuid>da658365-64ad-43dc-8019-1a34d2861ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refferalCodeEventCode']</value>
      <webElementGuid>f32eac3b-0b26-45a9-bb1c-56b9edbbd17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refferalCodeEventCode_area']/input</value>
      <webElementGuid>c41afa8a-a792-4eec-a132-f615a0370408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>7b024f2e-6b4c-47df-91ea-86b47e87120b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'refferalCodeEventCode' and @id = 'refferalCodeEventCode' and @placeholder = 'Masukkan Kode Referal Teman Anda Disini']</value>
      <webElementGuid>1248ae6c-51b4-445f-aaad-c1b138149284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
