<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Kode Event (opsional)</name>
   <tag></tag>
   <elementGuidId>80146a39-cb06-4ade-b854-61dfd5490914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refferalCodeEventCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refferalCodeEventCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92fdfebb-9764-41be-b48a-bec6569e0d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fa7ca24-5064-4b95-b51c-3035bf12f72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>3ce61e7d-5c8c-4b79-ad12-66f1eeb111dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>708b504f-cc7a-4c5a-a6a8-5717bedf9098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f72cee11-4270-4d13-9d37-34a3cbf68868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kode Event Disini</value>
      <webElementGuid>dde53426-9384-4c99-9a47-c437cfd5e693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refferalCodeEventCode&quot;)</value>
      <webElementGuid>a3a7cf2b-251f-4a62-912b-47901339db9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refferalCodeEventCode']</value>
      <webElementGuid>8e07c7b1-7f22-497a-b09d-551bda1b7615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refferalCodeEventCode_area']/input</value>
      <webElementGuid>d3a4a69a-0dfc-4703-99b7-810c8c8e02db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>c71f0eb8-4086-4737-b96f-008819d3f47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'refferalCodeEventCode' and @id = 'refferalCodeEventCode' and @placeholder = 'Masukkan Kode Event Disini']</value>
      <webElementGuid>a913460f-be3e-452f-bcd6-d1f77414b622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
