<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih Kondisi Mama saat ini</name>
   <tag></tag>
   <elementGuidId>750b84ad-3438-4172-b4d5-070cb098e66b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parent-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parent-status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f7de2bc-e5ec-4f7e-b736-81cfff3fd7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>5d48b8dc-dcfa-44de-92f7-6e08e6d73fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a72f2baf-ce36-4829-a309-ca74da7b8083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parent-status</value>
      <webElementGuid>8d30a6cf-2e3d-475e-bc8d-2b14f176a30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kondisi Mama</value>
      <webElementGuid>8a8b6d95-aab8-498f-96d2-911886083d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parent-status&quot;)</value>
      <webElementGuid>0a2ad28e-a3ec-4db1-9232-6a6b1103d165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parent-status']</value>
      <webElementGuid>8982bbd8-9555-4e0f-9188-1369e7800c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='motherCondition']/div/div/input[2]</value>
      <webElementGuid>804c9918-3693-4aca-84e7-ba27eb683d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input[2]</value>
      <webElementGuid>c46b6944-851e-441c-8cdf-d7081b54eb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'parent-status' and @placeholder = 'Pilih Kondisi Mama']</value>
      <webElementGuid>47897589-7d6c-405b-9e9c-31ddac191631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
