<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pointer Kode Referal</name>
   <tag></tag>
   <elementGuidId>277c1c1b-f3bf-4245-8f15-09e9e83190b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;isRefferalCodeEventCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='isRefferalCodeEventCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d604aea8-36f8-48ac-9ad4-d7f839c1b4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8cc681ec-91cc-4d8a-8f4e-da40194c7c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input is_code_refferal_event_code</value>
      <webElementGuid>0aff6c82-9deb-46df-9b30-2c6310fbfbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isRefferalCodeEventCode</value>
      <webElementGuid>26f33cc9-d782-4837-8238-20d356c96ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>refferalcode</value>
      <webElementGuid>79c19f62-808e-4182-bba9-3edc855b07b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/form[@class=&quot;registration recaptcha-form&quot;]/div[@class=&quot;content justify-content-center register&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-12 col-md-8&quot;]/div[@class=&quot;registration__form&quot;]/div[@class=&quot;registration__content mb-4&quot;]/div[@class=&quot;content__card rounded shadow --show-bg-card my-3 px-4&quot;]/div[@class=&quot;content__input referal-event&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 form-check&quot;]/input[@class=&quot;form-check-input is_code_refferal_event_code&quot;]</value>
      <webElementGuid>c1f2a669-227e-4891-ae0b-b0e9b705a00d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='isRefferalCodeEventCode']</value>
      <webElementGuid>ac5bfd61-0977-4571-a236-f0f4c5ec6463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>8d9f1a7a-9024-4444-bc77-cb9f9bb66271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'isRefferalCodeEventCode']</value>
      <webElementGuid>e54cbc05-19d7-4e59-95a0-d2f41c7fcad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
