<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Mulai_continue</name>
   <tag></tag>
   <elementGuidId>3b1c564a-bd23-48c1-8855-380858c162fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__st_bpn_yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__st_bpn_yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29f18070-922b-49f0-8979-35c7156f86a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0ed3dfc-fce1-45ca-a6be-47f446eaefae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continue</value>
      <webElementGuid>994d403a-ac3e-4e4e-afa4-8d7c0596344e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__st_bpn_yes</value>
      <webElementGuid>1eb1c295-53ee-4c44-b4b7-9b3eb77f0d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>MULAI</value>
      <webElementGuid>76105311-d83e-49c0-bd62-584f906fa316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_bpn_yes&quot;)</value>
      <webElementGuid>d84a245f-58a2-413f-8289-1c6bef66ebba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Popup/iframe popup Nanti-Mulai</value>
      <webElementGuid>a1c50bf7-41ec-466b-8026-6332e7befdad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__st_bpn_yes']</value>
      <webElementGuid>f7f9430d-337e-442a-9020-faa99b8c9d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>2ad23883-8558-401f-929f-33a7d6a1374d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'continue' and @id = '__st_bpn_yes']</value>
      <webElementGuid>5141caa6-ee2a-4b85-aa1f-3bd4efef63a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
