<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Nanti_notnow</name>
   <tag></tag>
   <elementGuidId>edf59001-35af-4da0-a04f-554ca755072c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__st_bpn_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__st_bpn_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b61e9a9-1437-41aa-9168-8521409b6493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fb70ac9-2d3d-4c0c-8aa5-ae479764fc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notnow</value>
      <webElementGuid>3a5af937-f53f-4a2e-9760-cc556539e3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__st_bpn_no</value>
      <webElementGuid>a3930592-af0c-456b-980f-bc3f5659ae28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NANTI</value>
      <webElementGuid>3af7ad65-7df3-47bf-88bb-fa9a2a782b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_bpn_no&quot;)</value>
      <webElementGuid>34977fd6-24f1-483a-abc1-cc5c79d0cc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Popup/iframe popup Nanti-Mulai</value>
      <webElementGuid>dcec33d0-8512-4149-90af-b589165363c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__st_bpn_no']</value>
      <webElementGuid>bbcb5cfc-913b-494c-8318-9370b1b5f848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f3dc28f5-1bd0-4077-8759-1719bbf96b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'notnow' and @id = '__st_bpn_no']</value>
      <webElementGuid>2e426fb8-fc00-45e8-ac9c-e998099f5288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
